FROM golang AS builder

WORKDIR /go/src/app
COPY server.go .
ARG CGO_ENABLED=0
RUN go get && go build -o server .

FROM alpine

WORKDIR /app
COPY --from=builder /go/src/app/server .
EXPOSE 8080
CMD ./server

